/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_github_yws179_speex_SpeexDecoder */

#ifndef _Included_com_github_yws179_speex_SpeexDecoder
#define _Included_com_github_yws179_speex_SpeexDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_yws179_speex_SpeexDecoder
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_yws179_speex_SpeexDecoder_init
  (JNIEnv *, jclass);

/*
 * Class:     com_github_yws179_speex_SpeexDecoder
 * Method:    decode
 * Signature: ([BI)[S
 */
JNIEXPORT jshortArray JNICALL Java_com_github_yws179_speex_SpeexDecoder_decode
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_github_yws179_speex_SpeexDecoder
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_yws179_speex_SpeexDecoder_destroy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
